language: php
php:
  - 7.3
  - 7.4
  - nightly
env:
  - GROUP=default

stages:
  - analyze
  - test
  - integration

jobs:
  fast_finish: true
  allow_failures:
    - php: nightly
    - stage: integration
  include:
    - stage: integration
      php: 7.3
      env:
        - GROUP=integration
    - stage: analyze
      php: 7.3
      install:
        - pecl install ast
        - phpenv config-rm xdebug.ini
        - composer install --prefer-dist
      script:
        - make ci-analyze --keep-going
        - composer validate

cache:
  directories:
    - $HOME/.composer
    - $HOME/.cache
    - build/cache

install:
  - phpenv config-rm xdebug.ini || true
  - composer remove --no-update --dev
      phan/phan phpstan/phpstan vimeo/psalm
      infection/infection friendsofphp/php-cs-fixer
  - if [[ $TRAVIS_PHP_VERSION = nightly ]]; then export COMPOSER_FLAGS="--ignore-platform-reqs"; fi
  - travis_retry composer install --prefer-dist $COMPOSER_FLAGS

script:
  - make ci-test --keep-going PHPUNIT_GROUP=$GROUP

after_success:
  - travis_retry php vendor/bin/php-coveralls
